blank_issues_enabled: false
contact_links:
  - name: Blog
    url: https://blog.tomanote.app
    about: Read articles, changelogs, and tips on the official TomaNote blog
  - name: Documentation
    url: https://docs.tomanote.app
    about: Read the official TomaNote documentation
